services:
  - type: web
    name: unamba-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_USUARIO
        sync: false
      - key: ADMIN_CONTRASENA
        sync: false
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: ADMIN_TOKEN_HOURS
        value: "8"